### ISSUE TITLE
AppDelegateのUINavigationBarの色の変更について

### ISSUE THREAD

**Issue by arusu0629** [bonegollira/GitOdo#44]
どうも、こんにちは。
現在Swift勉強中で、GitOdoを写経中でつまずいた部分について質問したいのですが

``` swift
UINavigationBar.apperance().barTintColor = rgba(44, 93, 142)
```

の部分が上手くいっていないのか、画面上でナビゲーションバーの色が変わりません
実装中にこのような問題にあたってことはありますでしょうか？

**Comment by bonegollira** [comment]
こんにちは！
うーん、なんででしょうね、、、
Storyboardで`UINavigationController`を紐付けてしまっている場合はStoryboard上の色の設定が反映されるのでは？とかですかね？

僕は
- iOS8, iPhone6

でしか確認していないのでiOS7とかではもしかしたらコードを追加しないといけないのかもしれません。

**Comment by arusu0629** [comment]
小林さん、お返事ありがとうございます。
少し調べてみたところ以下のサイトを参考に
http://www51.atwiki.jp/appwiki/pages/48.html http://www51.atwiki.jp/appwiki/pages/48.html

AppDelegateの方に

・UINavigationBar.appearance().translucent = false

を追加することで問題回避することができました。
ありがとうございました。

**Comment by bonegollira** [comment]
なるほど、僕も勉強になりました、ありがとうございます！
